name: Package addon

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q
          config: https://raw.githubusercontent.com/BigWigsMods/BigWigs/master/.luacheckrc

      - name: Download common locale
        if: always()
        run: |
          mkdir -p Core/Locales
          curl -sS https://raw.githubusercontent.com/BigWigsMods/BigWigs/master/Core/Locales/common.enUS.lua > Core/Locales/common.enUS.lua

      - name: Update option files (Retail)
        if: always()
        uses: BigWigsMods/actions/gen-options@master
        with:
          path: LittleWigs_Mainline.toc

      - name: Update option files (Classic Era Vanilla)
        if: always()
        uses: BigWigsMods/actions/gen-options@master
        with:
          path: LittleWigs_Vanilla.toc

      - name: Update option files (Burning Crusade Classic)
        if: always()
        uses: BigWigsMods/actions/gen-options@master
        with:
          path: LittleWigs_TBC.toc

      - name: Update option files (Wrath Classic)
        if: always()
        uses: BigWigsMods/actions/gen-options@master
        with:
          path: LittleWigs_Wrath.toc

      - name: Update option files (Cataclysm Classic)
        if: always()
        uses: BigWigsMods/actions/gen-options@master
        with:
          path: LittleWigs_Cata.toc

      - name: Package
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
