name: Check PR

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v2

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q
          config: https://raw.githubusercontent.com/BigWigsMods/BigWigs/master/.luacheckrc

      - name: Download common locale
        if: always()
        run: |
          mkdir -p Core/Locales
          curl -sS https://raw.githubusercontent.com/BigWigsMods/BigWigs/master/Core/Locales/common.enUS.lua > Core/Locales/common.enUS.lua

      - name: Lint boss modules
        if: always()
        uses: BigWigsMods/actions/gen-options@master
        with:
          quiet: true
          lint: true
