name: Check PR

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q
          config: https://raw.githubusercontent.com/BigWigsMods/BigWigs/master/.luacheckrc

      - name: Download common locale
        if: always()
        run: |
          mkdir -p Locales
          curl -sSf https://raw.githubusercontent.com/BigWigsMods/BigWigs/master/Locales/enUS_common.lua > Locales/enUS_common.lua

      - name: Lint boss modules (Retail)
        if: always()
        uses: BigWigsMods/actions/gen-options@master
        with:
          path: LittleWigs_Mainline.toc
          quiet: true
          lint: true

      - name: Lint boss modules (Classic Era Vanilla)
        if: always()
        uses: BigWigsMods/actions/gen-options@master
        with:
          path: LittleWigs_Vanilla.toc
          quiet: true
          lint: true

      - name: Lint boss modules (Burning Crusade Classic)
        if: always()
        uses: BigWigsMods/actions/gen-options@master
        with:
          path: LittleWigs_TBC.toc
          quiet: true
          lint: true

      - name: Lint boss modules (Wrath Classic)
        if: always()
        uses: BigWigsMods/actions/gen-options@master
        with:
          path: LittleWigs_Wrath.toc
          quiet: true
          lint: true

      - name: Lint boss modules (Cataclysm Classic)
        if: always()
        uses: BigWigsMods/actions/gen-options@master
        with:
          path: LittleWigs_Cata.toc
          quiet: true
          lint: true
